### ISSUE TITLE
Use resources.getString instead of raw string

### ISSUE THREAD

**Issue by vmichalak** [vincent-heng/climbstats-app#6]
https://github.com/vincent-heng/climbstats-app/blob/fb49be459f1d017aa4b0fd487c20d2281fa20f2e/src/main/java/fr/ippon/climbstats/PersonalChartActivity.kt#L109

**Comment by vincent-heng** [comment]
Fixed by 469b0943c7a784dc0eb14cdbc843b2c3406ac629 aswell
